"""new Models Patient and SelfPaid

Revision ID: 1bd6b81cdaed
Revises: 37c9e4671f7d
Create Date: 2018-03-29 18:21:56.140000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd6b81cdaed'
down_revision = '37c9e4671f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient'), 'patients', ['patient'], unique=False)
    op.create_table('self_paid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'pkvinvoice', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pkvinvoice', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pkvinvoice', type_='foreignkey')
    op.drop_column(u'pkvinvoice', 'patient_id')
    op.drop_table('self_paid')
    op.drop_index(op.f('ix_patients_patient'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
