"""added new field informed_me

Revision ID: 287fb0e5c085
Revises: 31e000cb8d8b
Create Date: 2018-04-05 10:52:37.055000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287fb0e5c085'
down_revision = '31e000cb8d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pkvinvoice', sa.Column('informed_me', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pkvinvoice', 'informed_me')
    # ### end Alembic commands ###
