"""new fields

Revision ID: 37c9e4671f7d
Revises: 134aa55ead92
Create Date: 2018-03-29 16:13:07.965000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c9e4671f7d'
down_revision = '134aa55ead92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pkvinvoice', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('pkvinvoice', sa.Column('invoice_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pkvinvoice', 'invoice_date')
    op.drop_column('pkvinvoice', 'due_date')
    # ### end Alembic commands ###
