"""removed obsolete boolean fields

Revision ID: e84ba65faf50
Revises: 287fb0e5c085
Create Date: 2018-04-05 11:04:56.319000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84ba65faf50'
down_revision = '287fb0e5c085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pkvinvoice', 'sent_to_pkv')
    op.drop_column('pkvinvoice', 'paid')
    op.drop_column('pkvinvoice', 'repaid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pkvinvoice', sa.Column('repaid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pkvinvoice', sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pkvinvoice', sa.Column('sent_to_pkv', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
